language: R
cache: packages

r_check_args: --as-cran --run-donttest

r_packages:
    - covr

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
      - libudunits2-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev

services:
  - docker

before_install:
- docker pull mongo
- docker run -d -p 27017:27017 --name mongodb mongo

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
